#!/usr/bin/env python3
"""Interactive setup wizard for Basement Cowboy."""

import os
import sys
import json
from pathlib import Path
from getpass import getpass


def print_header():
    """Print setup wizard header."""
    print("\n" + "=" * 60)
    print("  🤠 Basement Cowboy - Setup Wizard")
    print("  AI-Powered News Aggregation Platform")
    print("=" * 60 + "\n")


def print_step(step: int, total: int, title: str):
    """Print step header."""
    print(f"\n[Step {step}/{total}] {title}")
    print("-" * 40)


def get_input(prompt: str, default: str = "", required: bool = True, secret: bool = False) -> str:
    """Get user input with optional default."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "

    while True:
        if secret:
            value = getpass(prompt)
        else:
            value = input(prompt)

        value = value.strip() or default

        if required and not value:
            print("  ❌ This field is required.")
            continue

        return value


def get_yes_no(prompt: str, default: bool = True) -> bool:
    """Get yes/no input."""
    default_str = "Y/n" if default else "y/N"
    while True:
        value = input(f"{prompt} [{default_str}]: ").strip().lower()
        if not value:
            return default
        if value in ('y', 'yes'):
            return True
        if value in ('n', 'no'):
            return False
        print("  Please enter 'y' or 'n'")


def check_python_version():
    """Check Python version."""
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 9):
        print(f"  ⚠️  Python 3.9+ recommended. You have {version.major}.{version.minor}")
        return False
    print(f"  ✅ Python {version.major}.{version.minor}.{version.micro}")
    return True


def check_dependencies():
    """Check required dependencies."""
    required = ['flask', 'requests', 'beautifulsoup4']
    missing = []

    for package in required:
        try:
            __import__(package.replace('-', '_'))
            print(f"  ✅ {package}")
        except ImportError:
            print(f"  ❌ {package} (missing)")
            missing.append(package)

    return missing


def setup_directories():
    """Create required directories."""
    directories = [
        'output/news_articles',
        'output/wordpress-output',
        'output/logs',
        'output/cache',
        'data',
    ]

    for dir_path in directories:
        Path(dir_path).mkdir(parents=True, exist_ok=True)
        print(f"  ✅ Created {dir_path}/")


def setup_env_file(config: dict):
    """Create or update .env file."""
    env_path = Path('.env')

    # Read existing .env if present
    existing = {}
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    existing[key] = value

    # Merge with new config
    existing.update(config)

    # Write .env
    with open(env_path, 'w') as f:
        f.write("# Basement Cowboy Configuration\n")
        f.write("# Generated by setup wizard\n\n")

        f.write("# Flask Settings\n")
        f.write(f"FLASK_DEBUG={existing.get('FLASK_DEBUG', 'false')}\n")
        f.write(f"SECRET_KEY={existing.get('SECRET_KEY', 'change-this-in-production')}\n\n")

        f.write("# OpenAI Settings\n")
        f.write(f"OPENAI_API_KEY={existing.get('OPENAI_API_KEY', '')}\n\n")

        f.write("# WordPress Settings\n")
        f.write(f"WORDPRESS_URL={existing.get('WORDPRESS_URL', '')}\n")
        f.write(f"WORDPRESS_USERNAME={existing.get('WORDPRESS_USERNAME', '')}\n")
        f.write(f"WORDPRESS_PASSWORD={existing.get('WORDPRESS_PASSWORD', '')}\n\n")

        f.write("# Scraper Settings\n")
        f.write(f"SCRAPER_MAX_ARTICLES={existing.get('SCRAPER_MAX_ARTICLES', '100')}\n")
        f.write(f"SCRAPER_DELAY={existing.get('SCRAPER_DELAY', '1.0')}\n")

    print("  ✅ Created .env file")


def setup_wordpress_config(config: dict):
    """Create WordPress config file."""
    wp_config = {
        'site_url': config.get('WORDPRESS_URL', ''),
        'username': config.get('WORDPRESS_USERNAME', ''),
        'graphql_endpoint': '/graphql',
        'rest_endpoint': '/wp-json/wp/v2',
        'default_status': 'draft',
    }

    config_path = Path('config/wordpress_config.json')
    config_path.parent.mkdir(parents=True, exist_ok=True)

    with open(config_path, 'w') as f:
        json.dump(wp_config, f, indent=2)

    print("  ✅ Created config/wordpress_config.json")


def run_setup():
    """Run the setup wizard."""
    print_header()

    config = {}

    # Step 1: Check requirements
    print_step(1, 5, "Checking Requirements")
    check_python_version()
    missing = check_dependencies()
    if missing:
        print(f"\n  ⚠️  Missing packages: {', '.join(missing)}")
        print("  Run: pip install -r requirements.txt")
        if not get_yes_no("Continue anyway?", default=False):
            return

    # Step 2: Setup directories
    print_step(2, 5, "Setting Up Directories")
    setup_directories()

    # Step 3: OpenAI Configuration
    print_step(3, 5, "OpenAI Configuration")
    print("  OpenAI is used for article summaries and image generation.")
    if get_yes_no("Configure OpenAI API?", default=True):
        config['OPENAI_API_KEY'] = get_input("OpenAI API Key", secret=True)
    else:
        print("  ℹ️  You can add your API key later in the web interface.")

    # Step 4: WordPress Configuration
    print_step(4, 5, "WordPress Configuration")
    print("  WordPress is used for publishing articles.")
    if get_yes_no("Configure WordPress?", default=True):
        config['WORDPRESS_URL'] = get_input("WordPress Site URL", "https://your-site.com")
        config['WORDPRESS_USERNAME'] = get_input("WordPress Username")
        config['WORDPRESS_PASSWORD'] = get_input("WordPress Application Password", secret=True)
    else:
        print("  ℹ️  You can configure WordPress later.")

    # Step 5: Create config files
    print_step(5, 5, "Creating Configuration Files")
    config['FLASK_DEBUG'] = 'true' if get_yes_no("Enable debug mode?", default=False) else 'false'
    config['SECRET_KEY'] = os.urandom(24).hex()

    setup_env_file(config)
    if config.get('WORDPRESS_URL'):
        setup_wordpress_config(config)

    # Complete
    print("\n" + "=" * 60)
    print("  ✅ Setup Complete!")
    print("=" * 60)
    print("\n  To start the application:")
    print("    python run.py")
    print("\n  Or with Docker:")
    print("    docker-compose up")
    print("\n  Access the web interface at: http://localhost:5000")
    print()


if __name__ == '__main__':
    try:
        run_setup()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
